# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('blst-example', ['blst'])
    obj.source = 'blst-example.cc'
    obj.includes = [obj.includes, '/home/vlado/ndnSIM/ns-3/src/blst/blst']
    obj.libpath = '/home/vlado/ndnSIM/ns-3/src/blst/blst'
    obj.lib = 'blst'

